# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160724_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='doors',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u0432\u0435\u0440\u0435\u0439 (\u0448\u043a\u0430\u0444)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, choices=[(0, 0), (80, 80), (90, 90), (120, 120), (140, 140), (160, 160), (180, 180)], default=0, verbose_name='\u0414\u043b\u0438\u043d\u0430 \u043a\u0440\u043e\u0432\u0430\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='product',
            name='module_mebel',
            field=models.CharField(blank=True, choices=[('\u0428\u043a\u0430\u0444', '\u0428\u043a\u0430\u0444'), ('\u041a\u0440\u043e\u0432\u0430\u0442\u044c', '\u041a\u0440\u043e\u0432\u0430\u0442\u044c'), ('\u0414\u0438\u0432\u0430\u043d', '\u0414\u0438\u0432\u0430\u043d'), ('\u041a\u0440\u0435\u0441\u043b\u043e', '\u041a\u0440\u0435\u0441\u043b\u043e'), ('\u0421\u0442\u0443\u043b', '\u0421\u0442\u0443\u043b'), ('\u0421\u0442\u043e\u043b', '\u0421\u0442\u043e\u043b'), ('\u0422\u0412-\u0442\u0443\u043c\u0431\u0430', '\u0422\u0412-\u0442\u0443\u043c\u0431\u0430'), ('\u0411\u0438\u0431\u043b\u0438\u043e\u0442\u0435\u043a\u0430', '\u0411\u0438\u0431\u043b\u0438\u043e\u0442\u0435\u043a\u0430'), ('\u041f\u0435\u0440\u0435\u0433\u043e\u0440\u043e\u0434\u043a\u0430', '\u041f\u0435\u0440\u0435\u0433\u043e\u0440\u043e\u0434\u043a\u0430'), ('\u0420\u0435\u0441\u0435\u043f\u0448\u043d', '\u0420\u0435\u0441\u0435\u043f\u0448\u043d'), ('\u041a\u0443\u0445\u043e\u043d\u043d\u044b\u0439 \u0443\u0433\u043e\u043b\u043e\u043a', '\u041a\u0443\u0445\u043e\u043d\u043d\u044b\u0439 \u0443\u0433\u043e\u043b\u043e\u043a'), ('\u0421\u0442\u043e\u0439\u043a\u0430', '\u0421\u0442\u043e\u0439\u043a\u0430'), ('\u041f\u0440\u0438\u043b\u0430\u0432\u043e\u043a', '\u041f\u0440\u0438\u043b\u0430\u0432\u043e\u043a')], max_length=100, verbose_name='\u0422\u0438\u043f \u043c\u043e\u0434\u0443\u043b\u044f \u043c\u0435\u0431\u0435\u043b\u0438'),
        ),
    ]
