# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_auto_20160804_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
            options={
                'ordering': ['date_added'],
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('terminal', models.CharField(blank=True, max_length=50, verbose_name='\u0422\u0435\u0440\u043c\u0438\u043d\u0430\u043b \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('site', models.CharField(blank=True, max_length=50, verbose_name='\u0421\u0430\u0439\u0442')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438',
                'verbose_name_plural': '\u0421\u043f\u043e\u0441\u043e\u0431\u044b \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d')),
                ('status', models.IntegerField(choices=[(1, '\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'), (2, '\u041f\u0440\u0438\u043d\u044f\u0442'), (3, '\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d'), (0, '\u041e\u0442\u043c\u0435\u043d\u0435\u043d'), (4, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('ip_address', models.GenericIPAddressField()),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u0418\u0437\u043c\u0435\u043d\u0435\u043d')),
                ('email', models.EmailField(max_length=50, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0439 \u043f\u043e\u0447\u0442\u044b')),
                ('telephone_1', models.CharField(max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('country', models.CharField(default='\u0420\u043e\u0441\u0441\u0438\u0439\u0441\u043a\u0430\u044f \u0424\u0435\u0434\u0435\u0440\u0430\u0446\u0438\u044f', max_length=50, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041a\u0440\u0430\u0439, \u043e\u0431\u043b\u0430\u0441\u0442\u044c, \u0440\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430')),
                ('city', models.CharField(help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: \u0433. \u041f\u0440\u043e\u0445\u043b\u0430\u0434\u043d\u044b\u0439 \u0438\u043b\u0438 \u0441. \u041c\u043e\u0441\u043a\u043e\u0432\u0441\u043a\u043e\u0435', max_length=50, null=True, verbose_name='\u041d\u0430\u0441\u0435\u043b\u0435\u043d\u043d\u044b\u0439 \u043f\u0443\u043d\u043a\u0442')),
                ('adress', models.CharField(help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: \u0443\u043b. \u041b\u0435\u043d\u0438\u043d\u0430 10 \u0438\u043b\u0438 \u043f\u0435\u0440. \u041a\u0440\u0430\u0441\u043d\u044b\u0439 5', max_length=100, null=True, verbose_name='\u0423\u043b\u0438\u0446\u0430, \u0434\u043e\u043c')),
                ('index', models.CharField(max_length=10, null=True, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0438\u043d\u0434\u0435\u043a\u0441')),
                ('skype', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0421\u043a\u0430\u0439\u043f')),
                ('payment', models.CharField(choices=[('\u041d\u0430\u043b\u0438\u0447\u043d\u044b\u0435', '\u041d\u0430\u043b\u0438\u0447\u043d\u044b\u0435'), ('\u0411\u0430\u043d\u043a\u043e\u0432\u0441\u043a\u0438\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434', '\u0411\u0430\u043d\u043a\u043e\u0432\u0441\u043a\u0438\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434'), ('\u0411\u0430\u043d\u043a\u043e\u0432\u0441\u043a\u0430\u044f \u043a\u0430\u0440\u0442\u0430', '\u0411\u0430\u043d\u043a\u043e\u0432\u0441\u043a\u0430\u044f \u043a\u0430\u0440\u0442\u0430'), ('\u0414\u0440\u0443\u0433\u043e\u0439', '\u0414\u0440\u0443\u0433\u043e\u0439')], default='\u041d\u0430\u043b\u0438\u0447\u043d\u044b\u0435', max_length=50, null=True, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Delivery', verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u0437\u0430\u043a\u0430\u0437\u0430',
                'verbose_name_plural': '\u041f\u043e\u0437\u0438\u0446\u0438\u0438 \u0437\u0430\u043a\u0430\u0437\u0430',
            },
        ),
    ]
